### ISSUE TITLE
Is this package working?

### ISSUE THREAD

**Issue by dmitriz** [fb55/entities#33]
```sh
± |master ✗| → npm install entities -S
encoding@0.1.0 /Users/dmitrizaitsev/test/encoding
└── entities@1.1.1 

 |system| Dmitris-MacBook-Pro in ~/test/encoding
± |master ✗| → node entities.js 
module.js:471
    throw err;
    ^

Error: Cannot find module 'entitites'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/dmitrizaitsev/test/encoding/entities.js:1:79)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

```js
var entitites = require('entitites')

console.log(
	entities.encodeHTML("&#38;")  // => "&amp;&num;38&semi;" 
)
```

**Comment by fb55** [comment]
You have a typo. The message is that `entitites` couldn't be found, which is missing an `i`.
