### ISSUE TITLE
Maximum call stack size exceeded on replace function.

### ISSUE THREAD

**Issue by cmarrero01** [fb55/entities#37]
home/ubuntu/crawler/crawler/node_modules/entities/lib/encode.js:58
                                .replace(re, func)
                                 ^

RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at Object.encodeXML (/home/ubuntu/crawler/crawler/node_modules/entities/lib/encode.js:58:6)
    at formatAttrs (/home/ubuntu/crawler/crawler/node_modules/dom-serializer/index.js:67:62)
    at renderTag (/home/ubuntu/crawler/crawler/node_modules/dom-serializer/index.js:132:17)
    at module.exports (/home/ubuntu/crawler/crawler/node_modules/dom-serializer/index.js:113:17)
    at renderTag (/home/ubuntu/crawler/crawler/node_modules/dom-serializer/index.js:146:14)
    at module.exports (/home/ubuntu/crawler/crawler/node_modules/dom-serializer/index.js:113:17)
    at renderTag (/home/ubuntu/crawler/crawler/node_modules/dom-serializer/index.js:146:14)
    at module.exports (/home/ubuntu/crawler/crawler/node_modules/dom-serializer/index.js:113:17)
    at renderTag (/home/ubuntu/crawler/crawler/node_modules/dom-serializer/index.js:146:14)
    at module.exports (/home/ubuntu/crawler/crawler/node_modules/dom-serializer/index.js:113:17)
    at renderTag (/home/ubuntu/crawler/crawler/node_modules/dom-serializer/index.js:146:14)
    at module.exports (/home/ubuntu/crawler/crawler/node_modules/dom-serializer/index.js:113:17)
    at renderTag (/home/ubuntu/crawler/crawler/node_modules/dom-serializer/index.js:146:14)
    at module.exports (/home/ubuntu/crawler/crawler/node_modules/dom-serializer/index.js:113:17)
    at renderTag (/home/ubuntu/crawler/crawler/node_modules/dom-serializer/index.js:146:14)

**Comment by fb55** [comment]
The stack trace doesn’t look like this is an issue with this library.

**Comment by cmarrero01** [comment]
@fb55 But the problem is with String.replace() function on encode: /node_modules/entities/lib/encode.js:58:6

You think that is a dom-serializer problem?
